### ISSUE TITLE
Plugin not working anymore, gets automatic disabled

### ISSUE THREAD

**Issue by MansVeer** [bwp91/homebridge-deebot#132]
### What issue do you have? Please be as thorough and explicit as possible.
The Deebot plugin gets disabled after starting/restarting HomeBridge

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebrid UI-X

* Which version of Homebridge/HOOBS do you have?
1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
node v18.15.0
NPM 9.6.1

* Which version of this plugin (homebridge-deebot) do you have? Has the issue started since upgrading from a previous version?
6.0.1
Not sure updated Rasbian from Buster to Bullseye AND updated the Deebot Plugin the next morning

* Which ECOVACS devices do you have that are causing issues? Please include product models if applicable.
Deebot OSMO 610 and Deebot N79t/w

### Please paste any relevant logs below.
[15/03/2023, 10:25:06 pm] Loaded plugin: homebridge-deebot@6.0.1
[15/03/2023, 10:25:06 pm] Registering platform 'homebridge-deebot.Deebot'

[15/03/2023, 10:25:09 pm] [Deebot] Initializing Deebot platform...
[15/03/2023, 10:25:09 pm] [Deebot] Initialising plugin v6.0.1 | System linux | Node v18.15.0 | HB v1.6.0 | HAPNodeJS v0.11.0...

[15/03/2023, 10:25:10 pm] [Deebot] Plugin initialised. Setting up accessories....
[15/03/2023, 10:25:10 pm] [Deebot] Using ecovacs-deebot library v0.9.3.

[15/03/2023, 10:25:14 pm] [Deebot] ***** Disabling plugin. *****
[15/03/2023, 10:25:14 pm] [Deebot] ***** getaddrinfo ENOTFOUND api-app.dc-ww.ww.ecouser.net at Function.AxiosError.from (/usr/lib/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****
[15/03/2023, 10:26:27 pm] [Homebridge UI] [homebridge-deebot] Terminating child process...
[15/03/2023, 10:26:27 pm] [Homebridge UI] [homebridge-deebot] Child process ended

**Comment by mrbungle64** [comment]
@MansVeer 

What country code are you using? Please try country code which is different to "WW":
https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/countries.json

**Comment by MansVeer** [comment]
@mrbungle64 

I'm using NZ

Just changed to WW but no success
[15/03/2023, 11:00:46 pm] [Deebot] ***** Disabling plugin. *****
[15/03/2023, 11:00:46 pm] [Deebot] ***** getaddrinfo ENOTFOUND gl-ww-api.ecovacs.com at Function.AxiosError.from (/usr/lib/node_modules/homebridge-deebot/node_modules/axios/lib/core/AxiosError.js:89:14). *****

**Comment by MansVeer** [comment]
@mrbungle64 

This is my config:
{
    "name": "Deebot",
    "useYeedi": false,
    "countryCode": "NZ",
    "username": "xxxxx",
    "password": "xxxxx",
    "platform": "Deebot"
}

**Comment by mrbungle64** [comment]
@MansVeer 

Please try country code which is **different** to "WW" and also the continent is **different** to "WW"

**Comment by mrbungle64** [comment]
You can use "ID" for example

**Comment by MansVeer** [comment]
@mrbungle64 

A million thanks!
Works again, strange NZ always worked but now on ID
